name: Decompile
on:
  push:
    branches: [ main ]
    paths:
    - Assembly-CSharp.dll
    - Assembly-CSharp-firstpass.dll
    - Plugins.Common.dll
    - Plugins.Data.dll
    - Plugins.Singletons.dll
  workflow_dispatch:
jobs:
  decompile:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Decompile Assembly-CSharp.dll
      uses: shabbywu/gh-action-ILSpyCmd@v1
      with:
        files: |
          Assembly-CSharp.dll
        output-dir: src/
        project: true
    - name: Decompile Assembly-CSharp-firstpass.dll
      uses: shabbywu/gh-action-ILSpyCmd@v1
      with:
        files: |
          Assembly-CSharp-firstpass.dll
        output-dir: src/
        project: true
    - name: Decompile Plugins.Common.dll
      uses: shabbywu/gh-action-ILSpyCmd@v1
      with:
        files: |
          Plugins.Common.dll
        output-dir: src/
        project: true
    - name: Decompile Plugins.Data.dll
      uses: shabbywu/gh-action-ILSpyCmd@v1
      with:
        files: |
          Plugins.Data.dll
        output-dir: src/
        project: true
    - name: Decompile Plugins.Singletons.dll
      uses: shabbywu/gh-action-ILSpyCmd@v1
      with:
        files: |
          Plugins.Singletons.dll
        output-dir: src/
        project: true
    - name: Fix permission
      run: |
        sudo chown -R $USER:$USER src
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ github.token }}
        title: 'Auto decompile csharp assembly'
        commit-message: 'Auto decompile csharp assembly'
        body: 'This PR is auto generated by GITHUB action'
        branch: 'gh-action'
        base: 'main'
        add-paths: |
          src/*
